name: Deploy to Droplet
on:
  push:
    branches:
      - main    # Se ejecuta solo cuando haces push a main (cámbialo si quieres otra rama)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start SSH agent and add private key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Deploy application via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            cd /var/www/myapp
            git pull origin main
            npm install
            pm2 restart all
          EOF
